### ISSUE TITLE
Undefined method `color?` for TTY::Screen::Class

### ISSUE THREAD

**Issue by muichkine** [peter-murach/tty-prompt#5]
Hello,

I have a code complaining as soon as I call `prompt = TTY::Prompt.new`.
Here is the trace:

    avril14th@avril14th:~/src/white2$ rake admin:organization:create
    rake aborted!
    NoMethodError: undefined method `color?' for TTY::Screen:Class
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/pastel-0.5.2/lib/pastel/color.rb:24:in `block in initialize'
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/pastel-0.5.2/lib/pastel/color.rb:24:in `fetch'
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/pastel-0.5.2/lib/pastel/color.rb:24:in `initialize'
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/pastel-0.5.2/lib/pastel.rb:32:in `new'
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/pastel-0.5.2/lib/pastel.rb:32:in `new'
    /home/avril14th/.rvm/gems/ruby-2.2.3/gems/tty-prompt-0.3.0/lib/tty/prompt.rb:57:in `initialize'
    /home/avril14th/src/white2/lib/tasks/admin.rake:9:in `new'
    /home/avril14th/src/white2/lib/tasks/admin.rake:9:in `block (3 levels) in <top (required)>'

I use `tty-prompt 0.30` in a Rails 4.2.5 app.

**Comment by muichkine** [comment]
Closed. Moved question to proper repository (https://github.com/peter-murach/pastel/issues/12)

**Comment by muichkine** [comment]
Moved to proper repository (https://github.com/peter-murach/pastel/issues/12).

**Comment by peter-murach** [comment]
Hi Olivier, sorry for this frustrating start. My bad, I have specified pastel dependencies wrongly by only restricting versions to minor instead of patch level. And virtually couple days ago I have released new `tty-screen` dep `v0.5.0` which I thought will be fine but `pastel` specified `v0.4` only which got happily upgraded - duhhh. I have rectified that and released `pastel v0.5.3` that has the fixed dependencies versions. Please install again and all should be fine - it is for me.

**Comment by muichkine** [comment]
Hey @peter-murach, no worries. :) Your gems are so cool man. Thank you so much. Cheers.
